# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Binary release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-windows:
    needs: create-release
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wxPython
        pip install pyinstaller

    - name: build executable
      run: |
        pyinstaller -F --add-data "./source/scandictionary.txt;." "./source/Scandroid.py"

    - uses: actions/upload-artifact@v2
      with:
        name: scandroid-windows
        path: dist/

  build-macos:
    needs: create-release
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wxPython
        pip install pyinstaller

    - name: build executable
      run: |
        pyinstaller -F --add-data "./source/scandictionary.txt:." "./source/Scandroid.py"

    - uses: actions/upload-artifact@v2
      with:
        name: scandroid-macos
        path: dist/

  create-release:
    runs-on: windows-latest
    needs: [build-windows, build-macos]

    - name: get windows artifact
        uses: actions/download-artifact@v2
        with:
          name: scandroid-windows

    - name: list
      run: |
      tree
      ls dist

    - name: get macos artifact
        uses: actions/download-artifact@v2
        with:
          name: scandroid-macos
  
    - name: list
      run: |
      tree
      ls dist
